language: node_js
node_js:
  - "node"

services:
  - mongodb
env:
  - DB_URL_TEST=mongodb://localhost:27017/test
  - CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
